# Generated by Django 3.1.2 on 2020-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BOXED', 'boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10)),
            ],
        ),
    ]
