# Generated by Django 3.1.2 on 2020-11-25 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0003_auto_20201029_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.CreateModel(
            name='Entry_Winx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DAMAGED CASE', 'Damaged Case'), ('FAILED BATTERY', 'Failed Battery'), ('CONNECTOR BROKEN', 'Connector Broken'), ('SWITCH BROKEN', 'Switch Broken'), ('NO SOLID WHITE', 'No Solid White'), ('IN SERVICE', 'In Service'), ('NO SOLID ORANGE', 'No Solid Orange')], default='In Service', max_length=18)),
                ('comments', models.TextField()),
                ('winx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.winx')),
            ],
            options={
                'verbose_name_plural': 'winx_entries',
            },
        ),
    ]
