# Generated by Django 3.1.2 on 2020-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0004_auto_20201125_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry_winx',
            name='status',
            field=models.CharField(choices=[('NO SOLID ORANGE', 'No Solid Orange'), ('IN SERVICE', 'In Service'), ('FAILED BATTERY', 'Failed Battery'), ('NO SOLID WHITE', 'No Solid White'), ('SWITCH BROKEN', 'Switch Broken'), ('CONNECTOR BROKEN', 'Connector Broken'), ('DAMAGED CASE', 'Damaged Case')], default='IN SERVICE', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
    ]
