# Generated by Django 3.1.2 on 2020-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0005_auto_20201125_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_winx',
            old_name='winx',
            new_name='winx_entry',
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry_winx',
            name='status',
            field=models.CharField(choices=[('SWITCH BROKEN', 'Switch Broken'), ('IN SERVICE', 'In Service'), ('CONNECTOR BROKEN', 'Connector Broken'), ('NO SOLID ORANGE', 'No Solid Orange'), ('NO SOLID WHITE', 'No Solid White'), ('DAMAGED CASE', 'Damaged Case'), ('FAILED BATTERY', 'Failed Battery')], default='IN SERVICE', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
    ]
