# Generated by Django 3.1.2 on 2020-11-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0006_auto_20201125_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry_winx',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry_winx',
            name='status',
            field=models.CharField(choices=[('CONNECTOR BROKEN', 'Connector Broken'), ('SWITCH BROKEN', 'Switch Broken'), ('NO SOLID WHITE', 'No Solid White'), ('DAMAGED CASE', 'Damaged Case'), ('NO SOLID ORANGE', 'No Solid Orange'), ('FAILED BATTERY', 'Failed Battery'), ('IN SERVICE', 'In Service')], default='IN SERVICE', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
    ]
