# Generated by Django 3.1.2 on 2020-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0008_auto_20201125_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('SWITCH BROKEN', 'Switch Broken'), ('NO SOLID WHITE', 'No Solid White'), ('IN SERVICE', 'In Service'), ('DAMAGED CASE', 'Damaged Case'), ('CONNECTOR BROKEN', 'Connector Broken'), ('NO SOLID ORANGE', 'No Solid Orange'), ('FAILED BATTERY', 'Failed Battery')], default='IN SERVICE', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
    ]
