# Generated by Django 3.1.2 on 2020-12-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0009_auto_20201201_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('FAILED BATTERY', 'Failed Battery'), ('IN SERVICE', 'In Service'), ('SWITCH BROKEN', 'Switch Broken'), ('DAMAGED CASE', 'Damaged Case'), ('NO SOLID ORANGE', 'No Solid Orange'), ('NO SOLID WHITE', 'No Solid White'), ('CONNECTOR BROKEN', 'Connector Broken')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
    ]
