# Generated by Django 3.1.2 on 2020-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0010_auto_20201201_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('AYR', 'Ayr'), ('AIN', 'Aintree'), ('BEV', 'Beverly'), ('CAR', 'Carlisle')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('FAILED', 'Failed'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('FAILED', 'Failed'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('FAILED', 'Failed'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('SWITCH BROKEN', 'Switch Broken'), ('DAMAGED CASE', 'Damaged Case'), ('IN SERVICE', 'In Service'), ('NO SOLID ORANGE', 'No Solid Orange'), ('NO SOLID WHITE', 'No Solid White'), ('FAILED BATTERY', 'Failed Battery'), ('CONNECTOR BROKEN', 'Connector Broken')], default='IN SERVICE', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('FAILED', 'Failed'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('FAILED', 'Failed'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('FAILED', 'Failed'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
    ]
