# Generated by Django 3.1.2 on 2020-12-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0011_auto_20201201_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('SWITCH BROKEN', 'Switch Broken'), ('IN SERVICE', 'In Service'), ('NO SOLID ORANGE', 'No Solid Orange'), ('CONNECTOR BROKEN', 'Connector Broken'), ('DAMAGED CASE', 'Damaged Case'), ('FAILED BATTERY', 'Failed Battery'), ('NO SOLID WHITE', 'No Solid White')], default='IN SERVICE', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('WIN', 'Wincanton'), ('MUS', 'Musselburgh'), ('KEL', 'KELSO'), ('AYR', 'Ayr'), ('NEWM', 'Newmarket'), ('GOO', 'Goodwood'), ('MR', 'Market Rasen'), ('HAY', 'Haydock Park'), ('TAU', 'Taunton'), ('EPS', 'Epsom Downs'), ('STR', 'Stratford-On-Avon'), ('CAT', 'Catterick Bridge'), ('AIN', 'Aintree'), ('SAN', 'Sandown Park'), ('CAR', 'Carlisle'), ('NEWB', 'Newbury'), ('WAR', 'Warwick'), ('SAL', 'Salisbury'), ('NOT', 'Nottingham'), ('RED', 'Redcar'), ('BEV', 'Beverly'), ('HAM', 'Hamilton Park'), ('HUN', 'Huntingdon'), ('KMP', 'Kempton Park'), ('PER', 'Perth'), ('LUD', 'Ludlow'), ('LEI', 'Leicester'), ('PON', 'Pontefract'), ('WET', 'Wetherby'), ('YOR', 'York'), ('THI', 'Thirsk'), ('EXE', 'Exeter'), ('CART', 'Cartmel'), ('CHES', 'Chester'), ('CHE', 'Cheltenham')], default='KMP', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('BOXED', 'Boxed')], default='STICK', max_length=10),
        ),
    ]
