# Generated by Django 3.1.2 on 2020-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0012_auto_20201201_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('NO SOLID ORANGE', 'No Solid Orange'), ('SWITCH BROKEN', 'Switch Broken'), ('NO SOLID WHITE', 'No Solid White'), ('CONNECTOR BROKEN', 'Connector Broken'), ('FAILED BATTERY', 'Failed Battery'), ('DAMAGED CASE', 'Damaged Case')], default='IN SERVICE', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Ayr', 'Ayr'), ('KEL', 'KELSO'), ('PER', 'Perth'), ('RED', 'Redcar'), ('HUN', 'Huntingdon'), ('LUD', 'Ludlow'), ('HAY', 'Haydock Park'), ('MR', 'Market Rasen'), ('PON', 'Pontefract'), ('WAR', 'Warwick'), ('SAL', 'Salisbury'), ('NOT', 'Nottingham'), ('STR', 'Stratford-On-Avon'), ('Kempton', 'Kempton Park'), ('CHES', 'Chester'), ('CAT', 'Catterick Bridge'), ('TAU', 'Taunton'), ('YOR', 'York'), ('CART', 'Cartmel'), ('CHE', 'Cheltenham'), ('NEWM', 'Newmarket'), ('NEWB', 'Newbury'), ('GOO', 'Goodwood'), ('THI', 'Thirsk'), ('CAR', 'Carlisle'), ('LEI', 'Leicester'), ('SAN', 'Sandown Park'), ('EPS', 'Epsom Downs'), ('Beverly', 'Beverly'), ('EXE', 'Exeter'), ('Aintree', 'Aintree'), ('HAM', 'Hamilton Park'), ('WET', 'Wetherby'), ('MUS', 'Musselburgh'), ('WIN', 'Wincanton')], default='Kempton', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
    ]
