# Generated by Django 3.1.2 on 2020-12-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0013_auto_20201201_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Switch Broken', 'Switch Broken'), ('Damaged Case', 'Damaged Case'), ('No Solid White', 'No Solid White'), ('Connector Broken', 'Connector Broken'), ('No Solid Orange', 'No Solid Orange'), ('Failed Battery', 'Failed Battery')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Wetherby', 'Wetherby'), ('Cartmel', 'Cartmel'), ('Carlisle', 'Carlisle'), ('Ludlow', 'Ludlow'), ('Sandown Park', 'Sandown Park'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Haydock', 'Haydock Park'), ('Perth', 'Perth'), ('Warwick', 'Warwick'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Chester', 'Chester'), ('Kempton Park', 'Kempton Park'), ('Pontefract', 'Pontefract'), ('Ayr', 'Ayr'), ('Goodwood', 'Goodwood'), ('Aintree', 'Aintree'), ('Musselburgh', 'Musselburgh'), ('Market Rasen', 'Market Rasen'), ('Catterick Bridge', 'Catterick Bridge'), ('Hamilton', 'Hamilton Park'), ('Thirsk', 'Thirsk'), ('Newbury', 'Newbury'), ('Newmarket', 'Newmarket'), ('Redcar', 'Redcar'), ('Taunton', 'Taunton'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Beverly', 'Beverly'), ('Huntingdon', 'Huntingdon'), ('Salisbury', 'Salisbury'), ('Kelso', 'Kelso'), ('York', 'York')], default='Kempton', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
    ]
