# Generated by Django 3.1.2 on 2020-12-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0014_auto_20201201_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White'), ('Switch Broken', 'Switch Broken'), ('Damaged Case', 'Damaged Case'), ('Failed Battery', 'Failed Battery'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Perth', 'Perth'), ('Newmarket', 'Newmarket'), ('Aintree', 'Aintree'), ('Pontefract', 'Pontefract'), ('Wincanton', 'Wincanton'), ('Wetherby', 'Wetherby'), ('Cheltenham', 'Cheltenham'), ('Leicester', 'Leicester'), ('Nottingham', 'Nottingham'), ('Kelso', 'Kelso'), ('Musselburgh', 'Musselburgh'), ('Taunton', 'Taunton'), ('Sandown Park', 'Sandown Park'), ('Ayr', 'Ayr'), ('Thirsk', 'Thirsk'), ('Catterick Bridge', 'Catterick Bridge'), ('Redcar', 'Redcar'), ('Kempton Park', 'Kempton Park'), ('Carlisle', 'Carlisle'), ('Epsom Downs', 'Epsom Downs'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Hamilton', 'Hamilton Park'), ('York', 'York'), ('Beverly', 'Beverly'), ('Exeter', 'Exeter'), ('Market Rasen', 'Market Rasen'), ('Warwick', 'Warwick'), ('Goodwood', 'Goodwood'), ('Haydock', 'Haydock Park'), ('Huntingdon', 'Huntingdon'), ('Newbury', 'Newbury'), ('Salisbury', 'Salisbury'), ('Cartmel', 'Cartmel'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester')], default='Kempton', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('BOXED', 'Boxed'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
    ]
