# Generated by Django 3.1.2 on 2020-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0016_auto_20201202_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Switch Broken', 'Switch Broken'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Wincanton', 'Wincanton'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Carlisle', 'Carlisle'), ('Epsom Downs', 'Epsom Downs'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Newmarket', 'Newmarket'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Cartmel', 'Cartmel'), ('Warwick', 'Warwick')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service'), ('Switch Broken', 'Switch Broken'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Wincanton', 'Wincanton'), ('Goodwood', 'Goodwood'), ('Wetherby', 'Wetherby'), ('Beverly', 'Beverly'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Kempton Park', 'Kempton Park'), ('Aintree', 'Aintree'), ('Market Rasen', 'Market Rasen'), ('Exeter', 'Exeter'), ('Hamilton', 'Hamilton Park'), ('Carlisle', 'Carlisle'), ('Epsom Downs', 'Epsom Downs'), ('Kelso', 'Kelso'), ('Leicester', 'Leicester'), ('Thirsk', 'Thirsk'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Newbury', 'Newbury'), ('Pontefract', 'Pontefract'), ('Salisbury', 'Salisbury'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Newmarket', 'Newmarket'), ('Chester', 'Chester'), ('Redcar', 'Redcar'), ('Perth', 'Perth'), ('Ludlow', 'Ludlow'), ('Cartmel', 'Cartmel'), ('Warwick', 'Warwick')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
    ]
