# Generated by Django 3.1.2 on 2020-12-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0017_auto_20201202_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('No Solid White', 'No Solid White'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Connector Broken', 'Connector Broken'), ('Failed Battery', 'Failed Battery')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Ludlow', 'Ludlow'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('No Solid White', 'No Solid White'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Connector Broken', 'Connector Broken'), ('Failed Battery', 'Failed Battery')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Ludlow', 'Ludlow'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.CreateModel(
            name='Arkle_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('No Solid White', 'No Solid White'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('Connector Broken', 'Connector Broken'), ('Failed Battery', 'Failed Battery')], default='In Service', max_length=18)),
                ('venue', models.CharField(choices=[('Sandown Park', 'Sandown Park'), ('Market Rasen', 'Market Rasen'), ('Kelso', 'Kelso'), ('Redcar', 'Redcar'), ('Hamilton', 'Hamilton Park'), ('Ludlow', 'Ludlow'), ('Catterick Bridge', 'Catterick Bridge'), ('Musselburgh', 'Musselburgh'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Newmarket', 'Newmarket'), ('Salisbury', 'Salisbury'), ('York', 'York'), ('Goodwood', 'Goodwood'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Leicester', 'Leicester'), ('Ayr', 'Ayr'), ('Huntingdon', 'Huntingdon'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Beverly', 'Beverly'), ('Thirsk', 'Thirsk'), ('Chester', 'Chester'), ('Pontefract', 'Pontefract'), ('Haydock', 'Haydock Park'), ('Wetherby', 'Wetherby'), ('Wincanton', 'Wincanton'), ('Epsom Downs', 'Epsom Downs'), ('Nottingham', 'Nottingham'), ('Taunton', 'Taunton'), ('Newbury', 'Newbury'), ('Carlisle', 'Carlisle')], default='Kempton Park', max_length=18)),
                ('comments', models.TextField(blank=True)),
                ('arkle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.arkle')),
            ],
            options={
                'verbose_name_plural': 'arkle entries',
            },
        ),
    ]
