# Generated by Django 3.1.2 on 2020-12-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0019_auto_20201202_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denman_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18)),
                ('venue', models.CharField(choices=[('Goodwood', 'Goodwood'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Beverly', 'Beverly'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Huntingdon', 'Huntingdon'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'denman entries',
            },
        ),
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Goodwood', 'Goodwood'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Beverly', 'Beverly'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Huntingdon', 'Huntingdon'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Goodwood', 'Goodwood'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Beverly', 'Beverly'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Huntingdon', 'Huntingdon'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('No Solid White', 'No Solid White'), ('In Service', 'In Service'), ('Connector Broken', 'Connector Broken'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Goodwood', 'Goodwood'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Beverly', 'Beverly'), ('Taunton', 'Taunton'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Sandown Park', 'Sandown Park'), ('Redcar', 'Redcar'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Chester', 'Chester'), ('Cartmel', 'Cartmel'), ('Kempton Park', 'Kempton Park'), ('Catterick Bridge', 'Catterick Bridge'), ('Newbury', 'Newbury'), ('Hamilton', 'Hamilton Park'), ('Leicester', 'Leicester'), ('Salisbury', 'Salisbury'), ('Carlisle', 'Carlisle'), ('Newmarket', 'Newmarket'), ('Thirsk', 'Thirsk'), ('York', 'York'), ('Exeter', 'Exeter'), ('Wincanton', 'Wincanton'), ('Wetherby', 'Wetherby'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs'), ('Musselburgh', 'Musselburgh'), ('Aintree', 'Aintree'), ('Kelso', 'Kelso'), ('Ayr', 'Ayr'), ('Huntingdon', 'Huntingdon'), ('Haydock', 'Haydock Park'), ('Nottingham', 'Nottingham'), ('Cheltenham', 'Cheltenham')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('BOXED', 'Boxed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.DeleteModel(
            name='Arkle_Denman',
        ),
        migrations.AddField(
            model_name='denman_entry',
            name='denman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.denman'),
        ),
    ]
