# Generated by Django 3.1.2 on 2020-12-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0020_auto_20201202_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Haydock', 'Haydock Park'), ('Huntingdon', 'Huntingdon'), ('Leicester', 'Leicester'), ('Exeter', 'Exeter'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Sandown Park', 'Sandown Park'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Warwick', 'Warwick'), ('Kempton Park', 'Kempton Park'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Epsom Downs', 'Epsom Downs'), ('Market Rasen', 'Market Rasen'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('York', 'York'), ('Perth', 'Perth'), ('Cheltenham', 'Cheltenham'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Haydock', 'Haydock Park'), ('Huntingdon', 'Huntingdon'), ('Leicester', 'Leicester'), ('Exeter', 'Exeter'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Sandown Park', 'Sandown Park'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Warwick', 'Warwick'), ('Kempton Park', 'Kempton Park'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Epsom Downs', 'Epsom Downs'), ('Market Rasen', 'Market Rasen'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('York', 'York'), ('Perth', 'Perth'), ('Cheltenham', 'Cheltenham'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Haydock', 'Haydock Park'), ('Huntingdon', 'Huntingdon'), ('Leicester', 'Leicester'), ('Exeter', 'Exeter'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Sandown Park', 'Sandown Park'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Warwick', 'Warwick'), ('Kempton Park', 'Kempton Park'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Epsom Downs', 'Epsom Downs'), ('Market Rasen', 'Market Rasen'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('York', 'York'), ('Perth', 'Perth'), ('Cheltenham', 'Cheltenham'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Cartmel', 'Cartmel'), ('Haydock', 'Haydock Park'), ('Huntingdon', 'Huntingdon'), ('Leicester', 'Leicester'), ('Exeter', 'Exeter'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Sandown Park', 'Sandown Park'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Warwick', 'Warwick'), ('Kempton Park', 'Kempton Park'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Epsom Downs', 'Epsom Downs'), ('Market Rasen', 'Market Rasen'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('York', 'York'), ('Perth', 'Perth'), ('Cheltenham', 'Cheltenham'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.CreateModel(
            name='Kauto_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken')], default='In Service', max_length=18)),
                ('venue', models.CharField(choices=[('Cartmel', 'Cartmel'), ('Haydock', 'Haydock Park'), ('Huntingdon', 'Huntingdon'), ('Leicester', 'Leicester'), ('Exeter', 'Exeter'), ('Pontefract', 'Pontefract'), ('Ludlow', 'Ludlow'), ('Sandown Park', 'Sandown Park'), ('Nottingham', 'Nottingham'), ('Wincanton', 'Wincanton'), ('Beverly', 'Beverly'), ('Kelso', 'Kelso'), ('Newmarket', 'Newmarket'), ('Catterick Bridge', 'Catterick Bridge'), ('Warwick', 'Warwick'), ('Kempton Park', 'Kempton Park'), ('Hamilton', 'Hamilton Park'), ('Redcar', 'Redcar'), ('Goodwood', 'Goodwood'), ('Taunton', 'Taunton'), ('Musselburgh', 'Musselburgh'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Thirsk', 'Thirsk'), ('Epsom Downs', 'Epsom Downs'), ('Market Rasen', 'Market Rasen'), ('Carlisle', 'Carlisle'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Ayr', 'Ayr'), ('Salisbury', 'Salisbury'), ('Aintree', 'Aintree'), ('York', 'York'), ('Perth', 'Perth'), ('Cheltenham', 'Cheltenham'), ('Wetherby', 'Wetherby')], default='Kempton Park', max_length=18)),
                ('comments', models.TextField(blank=True)),
                ('kauto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.kauto')),
            ],
            options={
                'verbose_name_plural': 'kauto entries',
            },
        ),
    ]
