# Generated by Django 3.1.2 on 2020-12-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0021_auto_20201202_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('York', 'York'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Huntingdon', 'Huntingdon'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Market Rasen', 'Market Rasen'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Haydock', 'Haydock Park'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('York', 'York'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Huntingdon', 'Huntingdon'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Market Rasen', 'Market Rasen'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Haydock', 'Haydock Park'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('York', 'York'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Huntingdon', 'Huntingdon'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Market Rasen', 'Market Rasen'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Haydock', 'Haydock Park'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('York', 'York'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Huntingdon', 'Huntingdon'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Market Rasen', 'Market Rasen'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Haydock', 'Haydock Park'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(choices=[('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('York', 'York'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Huntingdon', 'Huntingdon'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Market Rasen', 'Market Rasen'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Haydock', 'Haydock Park'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.CreateModel(
            name='Frankel_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Damaged Case', 'Damaged Case'), ('In Service', 'In Service'), ('Failed Battery', 'Failed Battery'), ('Connector Broken', 'Connector Broken'), ('Switch Broken', 'Switch Broken'), ('No Solid Orange', 'No Solid Orange'), ('No Solid White', 'No Solid White')], default='In Service', max_length=18)),
                ('venue', models.CharField(choices=[('Carlisle', 'Carlisle'), ('Kelso', 'Kelso'), ('Goodwood', 'Goodwood'), ('Thirsk', 'Thirsk'), ('Warwick', 'Warwick'), ('Perth', 'Perth'), ('Wincanton', 'Wincanton'), ('Pontefract', 'Pontefract'), ('Wetherby', 'Wetherby'), ('Nottingham', 'Nottingham'), ('Redcar', 'Redcar'), ('York', 'York'), ('Catterick Bridge', 'Catterick Bridge'), ('Beverly', 'Beverly'), ('Ayr', 'Ayr'), ('Cheltenham', 'Cheltenham'), ('Aintree', 'Aintree'), ('Exeter', 'Exeter'), ('Ludlow', 'Ludlow'), ('Newbury', 'Newbury'), ('Epsom Downs', 'Epsom Downs'), ('Chester', 'Chester'), ('Newmarket', 'Newmarket'), ('Cartmel', 'Cartmel'), ('Huntingdon', 'Huntingdon'), ('Musselburgh', 'Musselburgh'), ('Sandown Park', 'Sandown Park'), ('Kempton Park', 'Kempton Park'), ('Leicester', 'Leicester'), ('Market Rasen', 'Market Rasen'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('Taunton', 'Taunton'), ('Haydock', 'Haydock Park'), ('Hamilton', 'Hamilton Park'), ('Salisbury', 'Salisbury')], default='Kempton Park', max_length=18)),
                ('comments', models.TextField(blank=True)),
                ('frankel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_logs.frankel')),
            ],
            options={
                'verbose_name_plural': 'frankel entries',
            },
        ),
    ]
