# Generated by Django 3.1.4 on 2020-12-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0022_auto_20201202_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkle',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('NOT IN SERVICE', 'Not In Service'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=15),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='arkle_entry',
            name='venue',
            field=models.CharField(choices=[('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Pontefract', 'Pontefract'), ('Newmarket', 'Newmarket'), ('Warwick', 'Warwick'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('NOT IN SERVICE', 'Not In Service'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=15),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='denman_entry',
            name='venue',
            field=models.CharField(choices=[('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Pontefract', 'Pontefract'), ('Newmarket', 'Newmarket'), ('Warwick', 'Warwick'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('NOT IN SERVICE', 'Not In Service'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=15),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='enable_entry',
            name='venue',
            field=models.CharField(choices=[('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Pontefract', 'Pontefract'), ('Newmarket', 'Newmarket'), ('Warwick', 'Warwick'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='venue',
            field=models.CharField(choices=[('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Pontefract', 'Pontefract'), ('Newmarket', 'Newmarket'), ('Warwick', 'Warwick'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('NOT IN SERVICE', 'Not In Service'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=15),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='frankel_entry',
            name='venue',
            field=models.CharField(choices=[('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Pontefract', 'Pontefract'), ('Newmarket', 'Newmarket'), ('Warwick', 'Warwick'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto',
            name='status',
            field=models.CharField(choices=[('BOXED', 'Boxed'), ('MISSING', 'Missing'), ('FAILED', 'Failed'), ('STICK', 'Stick')], default='STICK', max_length=15),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='status',
            field=models.CharField(choices=[('Failed Battery', 'Failed Battery'), ('Switch Broken', 'Switch Broken'), ('Connector Broken', 'Connector Broken'), ('No Solid White', 'No Solid White'), ('Damaged Case', 'Damaged Case'), ('No Solid Orange', 'No Solid Orange'), ('In Service', 'In Service')], default='In Service', max_length=18),
        ),
        migrations.AlterField(
            model_name='kauto_entry',
            name='venue',
            field=models.CharField(choices=[('Catterick Bridge', 'Catterick Bridge'), ('Thirsk', 'Thirsk'), ('Hamilton', 'Hamilton Park'), ('Stratford-On-Avon', 'Stratford-On-Avon'), ('York', 'York'), ('Huntingdon', 'Huntingdon'), ('Ayr', 'Ayr'), ('Musselburgh', 'Musselburgh'), ('Ludlow', 'Ludlow'), ('Salisbury', 'Salisbury'), ('Beverly', 'Beverly'), ('Aintree', 'Aintree'), ('Redcar', 'Redcar'), ('Leicester', 'Leicester'), ('Taunton', 'Taunton'), ('Nottingham', 'Nottingham'), ('Kempton Park', 'Kempton Park'), ('Chester', 'Chester'), ('Newbury', 'Newbury'), ('Wincanton', 'Wincanton'), ('Cheltenham', 'Cheltenham'), ('Haydock', 'Haydock Park'), ('Cartmel', 'Cartmel'), ('Goodwood', 'Goodwood'), ('Sandown Park', 'Sandown Park'), ('Wetherby', 'Wetherby'), ('Carlisle', 'Carlisle'), ('Exeter', 'Exeter'), ('Perth', 'Perth'), ('Pontefract', 'Pontefract'), ('Newmarket', 'Newmarket'), ('Warwick', 'Warwick'), ('Kelso', 'Kelso'), ('Market Rasen', 'Market Rasen'), ('Epsom Downs', 'Epsom Downs')], default='Kempton Park', max_length=18),
        ),
        migrations.AlterField(
            model_name='winx',
            name='status',
            field=models.CharField(choices=[('IN SERVICE', 'In Service'), ('BOXED', 'Boxed'), ('STICK', 'Stick'), ('NOT IN SERVICE', 'Not In Service'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=15),
        ),
    ]
